// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCly2hjG9efL42guOMJNR38VHYDwrKfXoQ',
    appId: '1:107365365254:web:ae77d8e98c0a194798b587',
    messagingSenderId: '107365365254',
    projectId: 'dock-chat-fbace',
    authDomain: 'dock-chat-fbace.firebaseapp.com',
    storageBucket: 'dock-chat-fbace.appspot.com',
    measurementId: 'G-9DR39G3FP2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-Xxte6lqfGObd7fHTQyiwu5ZJ-b2kirU',
    appId: '1:107365365254:android:89a99a300e8482c698b587',
    messagingSenderId: '107365365254',
    projectId: 'dock-chat-fbace',
    storageBucket: 'dock-chat-fbace.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4PHIdNyKyWDY8moBle1Zrnu12Jo2i3X4',
    appId: '1:107365365254:ios:557cd3519af2024b98b587',
    messagingSenderId: '107365365254',
    projectId: 'dock-chat-fbace',
    storageBucket: 'dock-chat-fbace.appspot.com',
    iosClientId: '107365365254-0p8bgqj35cadfrs50qeg5errdt4v268b.apps.googleusercontent.com',
    iosBundleId: 'com.example.dockChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4PHIdNyKyWDY8moBle1Zrnu12Jo2i3X4',
    appId: '1:107365365254:ios:d400ccf7b01fc11098b587',
    messagingSenderId: '107365365254',
    projectId: 'dock-chat-fbace',
    storageBucket: 'dock-chat-fbace.appspot.com',
    iosClientId: '107365365254-hgeoi38s29i91nn04h489m3gcm9tnrhp.apps.googleusercontent.com',
    iosBundleId: 'com.example.dockChat.RunnerTests',
  );
}
